packages:
  - packages/*
  - apps/*

catalog:
  '@types/lodash.throttle': ^4.1.7
  '@types/node': ^22.10.5
  '@types/prismjs': ^1.26.5
  '@vitejs/plugin-vue': ^5.2.4
  '@vue/tsconfig': 0.7.0
  bumpp: ^9.7.1
  del-cli: ^6.0.0
  eslint: ^9.17.0
  is-url-superb: ^6.1.0
  katex: ^0.16.11
  lodash.throttle: ^4.1.1
  medium-zoom: ^1.1.0
  memoize: ^10.1.0
  normalize-url: ^8.0.1
  '@slogvo/notion-client': workspace:*
  '@slogvo/notion-types': workspace:*
  '@slogvo/notion-utils': workspace:*
  npm-run-all2: ^7.0.2
  ofetch: ^1.4.1
  p-map: ^7.0.3
  p-queue: ^8.1.0
  prettier: ^3.4.2
  prismjs: ^1.29.0
  simple-git-hooks: ^2.12.1
  tsup: ^8.3.5
  tsx: ^4.19.2
  turbo: ^2.3.3
  typescript: ^5.7.2
  vite: ^6.0.5
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-pdf-embed: ^2.1.1
  vue-tsc: ^2.1.10
